### ISSUE TITLE
Kebab-case instead of snake_case 

### ISSUE THREAD

**Issue by antononcube** [raku-community-modules/Algorithm-Diff#23]
The functions in this package have snake_case names:
`compact_diff`, `LCS_length`, `traverse_balanced`, `traverse_sequences`.

I think it is better if those functions are with kebab-case.
Alternatively, we can have kebab-case synonyms.

I do not feel very strongly about this, but since this package is re-adopted, I think this is the right time to change those names.

**Comment by lizmat** [comment]
I think this functionality needs a more thorough reconsidering using Raku features, rather than being a port from Perl.  Such a new approach could use kebab-case.  So closing this now.
